### ISSUE TITLE
FixtureMonkey Null 생성으로 에러 발생

### ISSUE THREAD

**Issue by yunyechan9893** [eco-dessert-platform/backend#171]
# 작성 이유
- Fixture Monkey는 builder()에서 setNotNull("컬럼명")을 사용하지 않으면 null값이 랜덤하게 생성되는 것을 확인
- 이로 인해 테스트 시 에러가 발생

# 개선 방법
- @NotNull 유효성 체크 어노테이션을 사용하면 Null이 안생김
- build() 메서드 사용 시 setNotNull("컬럼명") 메서드를 지정하는 것도 사실상 불가능에 가깝다고 생각됨
- 따라서 Entity 복제본 클래스를 만들어 @NotNull 유효성 체크를 적용한 클래스를 사용하는게 어떨까? 제안함
- 다른 더 좋은 대안이 있다면 그 대안으로 채택

# 예시
```java
public class MemberCopy {
    @NotNull
    private Long id;
    
    private String email;
    
    private String phone;

    ...

    public Member toEntity() {
        return Member.builder()
            .id(this.id)
            ...
            .build();
    }
}
```

**Comment by chung-A** [comment]
복제본클래스 만들면 관리가 더 힘들고 변경이 있을때 두번 변경해줘야해서 안좋은거같아요
차라리 null 이들어가면 안되는 값은 db 처럼 notnull 넣는게 나을거같아요
